import React, { useState } from 'react';
import { Link } from 'react-router-dom'
import axiosWithAuth from '../utils/axiosWithAuth'
import { useHistory } from 'react-router-dom'

const UpdateRecipe = () => {

    const [updatedRecipe, setUpdatedRecipe] = useState(
        {
            title: "",  // string, required
            source: "",  // string, optional
            ingredients: "",  // text, required
            instructions: "",  // text, required
            notes: "",  // text, optional
            categories: [ ]  // array of category ids*, optional
        }
    )

    const { push } = useHistory()

                // id:   // generated by database
            // user_id:   // automatically grabbed from authorization token

    const handleChanges = (input) => {
        setNewRecipe({...newRecipe, [input.target.name] : input.target.value})
        console.log('New Recipe:',newRecipe)
    }

    const handleSubmit = (e) => {
        axiosWithAuth().post('https://secret-fam-recipes.herokuapp.com/api/recipes', newRecipe)
        .then(console.log('New Recipe Added: ', newRecipe))
        push('/dashboard');
    }

    return (
        <div className='addRecipeBox'>
            <Link to='/dashboard'>Back to Dashboard</Link>
            <p>Add A Recipe</p>
            <form onSubmit={handleSubmit} className='addRecipeForm'>

                <input 
                    type='text' 
                    placeholder='Recipe Name'
                    name='title'
                    onChange={handleChanges}
                    required
                />
                <span className='requiredIndicator'>*</span>
                <br/>

                <input 
                    type='text' 
                    placeholder='Source of Recipe'
                    name='source'
                    onChange={handleChanges}
                />
                <br/>

                <textarea 
                    rows='4' 
                    cols="50" 
                    placeholder='Ingredients'
                    name='ingredients'
                    onChange={handleChanges}
                    required
                /> 
                <span className='requiredIndicator'>*</span>
                <br/>

                <textarea 
                    rows='4' 
                    cols="50" 
                    placeholder='Instructions'
                    name='instructions'
                    onChange={handleChanges}
                    required
                />
                <span className='requiredIndicator'>*</span>
                <br/>

                <textarea 
                    rows='4' 
                    cols="50" 
                    placeholder='Notes'
                    name='notes'
                    onChange={handleChanges}
                />
                <br/>

                <label for='breakfast'>Breakfast</label>
                <input value='1' type='checkbox' name='categories' onChange={handleChanges} />
                <br/>

                <label for='lunch'>Lunch</label>
                <input value='2' type='checkbox' name='categories' onChange={handleChanges} />
                <br/>

                <label for='dinner'>Dinner</label>
                <input value='3' type='checkbox' name='categories' onChange={handleChanges} />
                <br/>

                <label for='vegetarian'>Vegetarian</label>
                <input value='4' type='checkbox' name='categories' onChange={handleChanges} />
                <br/>

                <label for='vegan'>Vegan</label>
                <input value='5' type='checkbox' name='categories' onChange={handleChanges} />
                <br/>

                <label for='gluten-free'>Gluten-Free</label>
                <input value='6' type='checkbox' name='categories' onChange={handleChanges} />
                <br/>

                {/* <input 
                    name='categories'
                />
                <br/> */}

                <br/>           
                <input type='submit' className='submit'/>
                <br/>

            </form>
        </div>
    )
}

export default UpdateRecipe